print("         |\\              /|")
print("         | \\            / |")
print("         |  \\          /  |     /")
print("         |   \\________/   |_   /")
print("                             \\/")
print("                                           ")
print("                                ")
print("                                   ")
print("                                                 ")
print("                                               ")
print("                                                ")
print("                                                ")
print("                                                  ")