import turtle

def turtleinitial():
    t = turtle.Turtle()
    t.pensize(5)
    t.penup()
    t.goto(-100, 100)
    t.pendown()
    t.forward(75)
    t.backward(150)
    t.forward(75)
    t.right(90)
    t.forward(150)
    t.circle(-45, 180)
    t.penup()
    t.home()
    t.goto(25, 0)
    t.pendown()
    t.right(90)
    t.forward(100)
    t.backward(200)
    t.forward(100)
    t.left(90)
    t.forward(100)
    t.right(90)
    t.forward(100)
    t.backward(200)
    t.hideturtle()
    turtle.done()
turtleinitial()