print("Mark Zuckerberg, the co-founder Facebook, was born on May 14, 1984, in White Plains, New York.")
print("He co-founded Facebook during his time at Harvard University, but dropped out after his sophomore year to develope the company.")
print("Today, Mark Zuckerberg is a billionaire and is the CEO of Meta, a company that owns Facebook, Instagram, WhatsApp, and other products and services.")
text = input("Have you heard of this person before? ")
print("You:", text)
print("They are pretty cool, aren't they.")
