import turtle

def turtleolympic():
    t1 = turtle.Turtle()
    t2 = turtle.Turtle()
    t3 = turtle.Turtle()
    t4 = turtle.Turtle()
    t5 = turtle.Turtle()
    t1.penup()
    t2.penup()
    t3.penup()
    t4.penup()
    t5.penup()
    t1.pensize(7)
    t2.pensize(7)
    t3.pensize(7)
    t4.pensize(7)
    t5.pensize(7)
    t1.color("blue")
    t2.color("black")
    t3.color("red")
    t4.color("yellow")
    t5.color("green")
    t1.goto(-130, 0)
    t2.goto(0, 0)
    t3.goto(130, 0)
    t4.goto(-65, -50)
    t5.goto(65, -50)
    t1.pendown()
    t2.pendown()
    t3.pendown()
    t4.pendown()
    t5.pendown()
    t1.circle(50)
    t2.circle(50)
    t3.circle(50)
    t4.circle(50)
    t5.circle(50)
    turtle.done()
turtleolympic()